AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless URL Shortener with Analytics

Globals:
  Function:
    Timeout: 5
    Runtime: python3.12
    Tracing: Active
    MemorySize: 256

Resources:
  UrlTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: UrlTable
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl

  AnalyticsEvent:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: AnalyticsEvent
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/shorten/app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: UrlTable
      Events:
        ShortenApi:
          Type: Api
          Properties:
            Path: /shorten
            Method: POST

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/redirect/app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: UrlTable
        - EventBridgePutEventsPolicy:
            EventBusName: default
      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: GET

  AnalyticsProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/analytics/app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: AnalyticsEvent
      Events:
        AnalyticsEventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "url-shortener.redirect"
